Patch to allow build with EAOs openGL version
Since a recent OpenGL update, EAO's Centos 6 Starlink builds have been
failing when building vtk due to underclared values in glxext.h This
patch copies a fix from the current upstream to allow vtk to be built
again.

The error message which occurs is:
thirdparty/kitware/vtk/VTK/Rendering/OpenGL/vtkXOpenGLRenderWindow.cxx:31
/usr/include/GL/glxext.h:480: error: 'GLintptr' has not been declared
/usr/include/GL/glxext.h:480: error: 'GLintptr' has not been declared
/usr/include/GL/glxext.h:480: error: 'GLsizeiptr' has not been declared
/usr/include/GL/glxext.h:481: error: 'GLintptr' has not been declared
/usr/include/GL/glxext.h:481: error: 'GLintptr' has not been declared
/usr/include/GL/glxext.h:481: error: 'GLsizeiptr' has not been declared
make[4]: *** [Rendering/OpenGL/CMakeFiles/vtkRenderingOpenGL.dir/vtkXOpenGLRenderWindow.cxx.o] Error 1
make[3]: *** [Rendering/OpenGL/CMakeFiles